### ISSUE TITLE
填报问题

### ISSUE THREAD

**Issue by YangSen16520** [Crush465/hebust-temperature-auto-write#4]
登录成功
获取sid失败,请检查你的学号和密码是否填写正确
获取stuId qid 失败
获取信息有误
开始执行
判断填写情况失败

登录成功 但是在获取sid的时候提示学号密码错误 我换了几个账号都有问题

**Comment by Crush465** [comment]
![image](https://user-images.githubusercontent.com/82747197/175230261-d9fcd799-abc4-46e5-ba95-11df9e7cc155.png)

**Comment by Crush465** [comment]
代码已更新，新代码测试目前正常，抱歉，维护太难了，这是原理
https://mp.weixin.qq.com/s?__biz=MzkxNTI2NTY2MA==&mid=2247483683&idx=1&sn=4064954b8a7b17a6275f2c68ce81efcf&chksm=c1608030f617092643709bc364dd1761d919d6d99c6efa08886d4c18f790ee2c779d6430cd20&mpshare=1&scene=22&srcid=07264PfVBFmtdpCjpcApQbus&sharer_sharetime=1627279129196&sharer_shareid=683f9a1f7589d7cc3a1322cea1098b74#rd

**Comment by YangSen16520** [comment]
感谢帮助 我自己用selenium尝试写的时候有点问题 然后想来git这边找一下 感谢
